# Generated by Django 5.2.8 on 2026-01-31 11:02

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for preview', max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(help_text='Main blog content with rich text formatting')),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for blog post', null=True, upload_to='blog/featured/')),
                ('author', models.CharField(default='Aniket Verma', max_length=255)),
                ('tags', models.JSONField(default=list, help_text="List of tags (e.g., ['Python', 'Django', 'AI'])")),
                ('category', models.CharField(default='Technology', help_text='Blog category', max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('read_time', models.IntegerField(default=5, help_text='Estimated read time in minutes')),
                ('views', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords', max_length=255)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
