# Generated by Django 5.2.8 on 2026-02-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='resume_url',
        ),
        migrations.AddField(
            model_name='personaldata',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
