# Generated by Django 5.2.8 on 2026-02-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_valentineresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="valentineresponse",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
